<a href="https://colab.research.google.com/github/PhucNguyenAH/Learn-Pytorch/blob/master/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
print(y.grad_fn)

In [6]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [8]:
out.backward()

In [9]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
x = torch.randn(3, requires_grad=True)

y = x * 2
print(y)
print(y.data.norm())
while y.data.norm() < 1000:
  y = y * 2
print(y)

tensor([ 1.7082,  1.1805, -4.1195], grad_fn=<MulBackward0>)
tensor(4.6132)
tensor([  437.2939,   302.1961, -1054.5867], grad_fn=<MulBackward0>)


In [19]:
a, b = torch.rand((2,2)), torch.rand((2,2))
print(f"{a}; {b}")
print(torch.abs((a * b)))

var1 = torch.sum(torch.abs((a * b)), 1)
print("L1 Distance is : ", var1)

var2 = torch.norm(((a * b)), 1, -1)
print("Torch NORM L1 Distance is : ", var2)

var3 = torch.sum(((a * b)) ** 2, 1).sqrt()
print("L2 SDistance is : ", var3)

var4 = torch.norm(((a * b)), 2, -1)
print("Torch NORM L2 Distance is : ", var4)

tensor([[0.7545, 0.8793],
        [0.1637, 0.9877]]); tensor([[0.1314, 0.4514],
        [0.2410, 0.9527]])
tensor([[0.0992, 0.3969],
        [0.0394, 0.9410]])
L1 Distance is :  tensor([0.4961, 0.9804])
Torch NORM L1 Distance is :  tensor([0.4961, 0.9804])
L2 SDistance is :  tensor([0.4091, 0.9418])
Torch NORM L2 Distance is :  tensor([0.4091, 0.9418])


In [20]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [21]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


In [24]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
